In [1]:
import numpy as nm
ar = nm.array([[[1,0],[3,4],[3,1]]])
br = nm.array([9,1,7,8])
cr = nm.empty([2,5,3], dtype=int)
dr = nm.random.randint(0,11, 20)
er = nm.array(['A','B',1,2])
print(ar.shape)
FR = nm.array([1,2,3])
print(FR.shape)
x = FR.reshape(1,3)
print(x)
y = FR.reshape(3,1)
print(y)
print(x+y)

(1, 3, 2)
(3,)
[[1 2 3]]
[[1]
 [2]
 [3]]
[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [8]:
a =  257
b = 257
a is b

False

In [2]:
arr = nm.arange(1,10,2)
c = arr.copy()
v = arr.view()
c[1] = 22
print(arr)
print(c)
print(v)

[1 3 5 7 9]
[ 1 22  5  7  9]
[1 3 5 7 9]
